### ISSUE TITLE
Cogs Video X 1.5 Finetuning Quick questions

### ISSUE THREAD

**Issue by ArEnSc** [THUDM/CogVideo#602]
### System Info / 系統信息

Hey I am trying to do full finetuning for T2V and then I2V

I was wondering about the configurations.
I am using the SAT configuration and SAT variant of the finetuning code.

It seems like in your paper you mentioned that you did the 5-second training and 10-second training in separate stages, rather than using a bucketing technique. 

I have prepared my data so that each mp4 is 5 seconds and the labels for them are under 224 tokens.

It crashes with memory issues with 
Here are the settings I have changed.

  video_size: [ 768, 1360 ] # the video size in your final stage training
    fps: 16 # fps for the final stage of training 
    max_num_frames: 81 # 5 seconds of frames 
    skip_frms_num: 0 # Do not skip frames because it is already down sampled?

      num_frames: 81 # for 5 seconds and 161 for 10 seconds
      time_compressed_rate: 4
      latent_width: 180 #   should it be 180 ? 1360 / 8 ? 
      latent_height: 96 #  should it be 96 ? 768 / 8 ? 

  train_micro_batch_size_per_gpu: 1 # 1 training sample per gpu
during the encoding first stage at the 3D Cov

My guess is you preprocessed latents prior and that the loader should actually load in the latents as npz and the flag should be self.latent_input = true ?

      if frame > 1 and self.latent_input:
          x = x.permute(0, 2, 1, 3, 4).contiguous()
          return x * self.scale_factor  # already encoded

<img width="1520" alt="Screenshot 2024-12-13 223641" src="https://github.com/user-attachments/assets/e0d017c3-23a4-41f4-b2ef-0269b62ff582" />
I am guessing you just preprocessed the latents before to avoid this memory issue ?
The full settings are below.
```
args:
  checkpoint_activations: True # using gradient checkpointing
  model_parallel_size: 1
  experiment_name: fine-tune-bunny
  mode: finetune
  load: "/home/ubuntu/cogvideo-fs-2/CrossProductExperimentsDoNotTouch/CogVideo/sat/CogVideoX1.5-5B-SAT/transformer_t2v"
  no_load_rng: True
  train_iters: 500 # Suggest more than 1000 For Lora and SFT For 500 is enough
  eval_iters: 1
  eval_interval: 100
  eval_batch_size: 1
  save: ckpts_5b_lora
  save_interval: 500
  log_interval: 20
  train_data: [ "/home/ubuntu/cogvideo-fs-2/CrossProductExperimentsDoNotTouch/CogVideo/sat/bunny-mini" ] # Train data path
  valid_data: [ "/home/ubuntu/cogvideo-fs-2/CrossProductExperimentsDoNotTouch/CogVideo/sat/bunny-mini" ] # Validation data path, can be the same as train_data(not recommended)
  split: 1,0,0
  num_workers: 1 # when set higher runs out of memory 
  force_train: True
  only_log_video_latents: True # Not sure what this is for what is it?

data:
  target: data_video.SFTDataset
  params:
    video_size: [ 768, 1360 ] # the video size in your final stage training
    fps: 16 # fps for the final stage training 
    max_num_frames: 81 # 5 seconds of frames 
    skip_frms_num: 0 # do not skip frames because it is already downsampled?

deepspeed:
  # Minimum for 16 videos per batch for ALL GPUs, This setting is for 8 x A100 GPUs
  train_micro_batch_size_per_gpu: 1 # 1 training sample per gpu
  gradient_accumulation_steps: 1
  steps_per_print: 50
  gradient_clipping: 0.1
  zero_optimization:
    stage: 2
    cpu_offload: false
    contiguous_gradients: false
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 1000000000
    allgather_bucket_size: 1000000000
    load_from_fp32_weights: false
  zero_allow_untested_optimizer: true
  bf16:
      enabled: True  # For CogVideoX-2B Turn to False and For CogVideoX-5B Turn to True
  fp16:
      enabled: False  # For CogVideoX-2B Turn to True and For CogVideoX-5B Turn to False
  loss_scale: 0
  loss_scale_window: 400
  hysteresis: 2
  min_loss_scale: 1

  optimizer:
    type: sat.ops.FusedEmaAdam
    params:
      lr: 0.00001 # Between 1E-3 and 5E-4 For Lora and 1E-5 For SFT
      betas: [ 0.9, 0.95 ]
      eps: 1e-8
      weight_decay: 1e-4
  activation_checkpointing:
    partition_activations: false
    contiguous_memory_optimization: false
  wall_clock_breakdown: false
```
```
model:
  scale_factor: 0.7
  disable_first_stage_autocast: true
  latent_input: false
  log_keys:
    - txt

  denoiser_config:
    target: sgm.modules.diffusionmodules.denoiser.DiscreteDenoiser
    params:
      num_idx: 1000
      quantize_c_noise: False

      weighting_config:
        target: sgm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
      scaling_config:
        target: sgm.modules.diffusionmodules.denoiser_scaling.VideoScaling
      discretization_config:
        target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization

  network_config:
    target: dit_video_concat.DiffusionTransformer
    params:
      time_embed_dim: 512
      elementwise_affine: True
      num_frames: 81 # for 5 seconds and 161 for 10 seconds
      time_compressed_rate: 4
      latent_width: 180 #  These are stock settings right? should it be 180 ? 1360 / 8 ? 
      latent_height: 96 # These are stock settings right? should it be 96 ? 768 / 8 ? 
      num_layers: 42
      patch_size: [2, 2, 2]
      in_channels: 16
      out_channels: 16
      hidden_size: 3072
      adm_in_channels: 256
      num_attention_heads: 48

      transformer_args:
        checkpoint_activations: True
        vocab_size: 1
        max_sequence_length: 64
        layernorm_order: pre
        skip_init: false
        model_parallel_size: 1
        is_decoder: false

      modules:
        pos_embed_config:
          target: dit_video_concat.Rotary3DPositionEmbeddingMixin
          params:
            hidden_size_head: 64
            text_length: 224

        patch_embed_config:
          target: dit_video_concat.ImagePatchEmbeddingMixin
          params:
            text_hidden_size: 4096

        adaln_layer_config:
          target: dit_video_concat.AdaLNMixin
          params:
            qk_ln: True

        final_layer_config:
          target: dit_video_concat.FinalLayerMixin

  conditioner_config:
    target: sgm.modules.GeneralConditioner
    params:
      emb_models:
          - is_trainable: false
            input_key: txt
            ucg_rate: 0.1
            target: sgm.modules.encoders.modules.FrozenT5Embedder
            params:
              model_dir: "/home/ubuntu/cogvideo-fs-2/CrossProductExperimentsDoNotTouch/CogVideo/sat/CogVideoX1.5-5B-SAT/t5-v1_1-xxl"
              max_length: 224


  first_stage_config:
    target : vae_modules.autoencoder.VideoAutoencoderInferenceWrapper
    params:
        cp_size: 1
        ckpt_path: "/home/ubuntu/cogvideo-fs-2/CrossProductExperimentsDoNotTouch/CogVideo/sat/CogVideoX1.5-5B-SAT/vae/3d-vae.pt"
        ignore_keys: ['loss']

        loss_config:
          target: torch.nn.Identity

        regularizer_config:
          target: vae_modules.regularizers.DiagonalGaussianRegularizer

        encoder_config:
          target: vae_modules.cp_enc_dec.ContextParallelEncoder3D
          params:
            double_z: true
            z_channels: 16
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1, 2, 2, 4]
            attn_resolutions: []
            num_res_blocks: 3
            dropout: 0.0
            gather_norm: True

        decoder_config:
          target: vae_modules.cp_enc_dec.ContextParallelDecoder3D
          params:
            double_z: True
            z_channels: 16
            resolution: 256
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1, 2, 2, 4]
            attn_resolutions: []
            num_res_blocks: 3
            dropout: 0.0
            gather_norm: True

  loss_fn_config:
    target: sgm.modules.diffusionmodules.loss.VideoDiffusionLoss
    params:
      offset_noise_level: 0
      sigma_sampler_config:
        target: sgm.modules.diffusionmodules.sigma_sampling.DiscreteSampling
        params:
          uniform_sampling: True
          group_num: 40
          num_idx: 1000
          discretization_config:
            target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization

  sampler_config:
    target: sgm.modules.diffusionmodules.sampling.VPSDEDPMPP2MSampler
    params:
      num_steps: 50
      verbose: True

      discretization_config:
        target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization
      guider_config:
        target: sgm.modules.diffusionmodules.guiders.DynamicCFG
        params:
          scale: 6
          exp: 5
          num_steps: 50
```

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.12              Driver Version: 550.90.12      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 PCIe               On  |   00000000:08:00.0 Off |                    0 |
| N/A   31C    P0             45W /  350W |      68MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   2792116      C   nvidia-cuda-mps-server                         58MiB |
+-----------------------------------------------------------------------------------------+
```

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Perform the steps above.

### Expected behavior / 期待表现

It should work with the correct settings suggested in the documentation for SAT
